# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HomeWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from ques1 import *

class Ui_Homewin(object):
    def setupUi(self, Homewin):
        Homewin.setObjectName("Homewin")
        Homewin.resize(669, 614)
        font = QtGui.QFont()
        font.setPointSize(10)
        Homewin.setFont(font)
        Homewin.setAutoFillBackground(False)
        Homewin.setStyleSheet("background-image:url(file:///C:/Users/Lenovo/PycharmProjects/Курсовой проект/test.jpg);")
        self.centralwidget = QtWidgets.QWidget(Homewin)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, 0, 681, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("home_back.jpg"))
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(100, 300, 411, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.T1 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.T1.setFont(font)
        self.T1.setObjectName("T1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.T1)
        self.B1 = QtWidgets.QPushButton(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.B1.setFont(font)
        self.B1.setObjectName("B1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.B1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(0, 30, 681, 231))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../OneDrive/Рабочий стол/картинки/66666.jpg"))
        self.label_3.setObjectName("label_3")
        Homewin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Homewin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 669, 26))
        self.menubar.setObjectName("menubar")
        Homewin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Homewin)
        self.statusbar.setObjectName("statusbar")
        Homewin.setStatusBar(self.statusbar)

        self.retranslateUi(Homewin)
        QtCore.QMetaObject.connectSlotsByName(Homewin)

    def retranslateUi(self, Homewin):
        _translate = QtCore.QCoreApplication.translate
        Homewin.setWindowTitle(_translate("Homewin", "Home Window"))
        self.label_2.setText(_translate("Homewin", "Введите имя"))
        self.B1.setText(_translate("Homewin", "Начать тест"))
        self.B1.clicked.connect(self.main_1) #обработка события нажать на кнопку
        self.B1.clicked.connect(Homewin.close)  #закрыть окно homewin

    def main_1(self):
        self.S1=self.T1.text()
        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_ques1(self.S1)
        self.ui.setupUi(self.queswin)
        self.queswin.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Homewin = QtWidgets.QMainWindow()
    ui = Ui_Homewin()
    ui.setupUi(Homewin)
    Homewin.show()
    sys.exit(app.exec_())