# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'resultwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *  # перенос имени
import sys


class Ui_resultwin(QtWidgets.QWidget):
    def __init__(self, name, count, total):  # перенос имени
        super().__init__()
        self.name = name  # имя
        self.count = count  # время 30 минут
        self.total = total  # правильные ответы
        self.count=1800-self.count
        self.S1 = str(self.count // 60)
        self.S2 = str(self.count % 60)
        self.S3 = self.S1 + '.' + self.S2

    def setupUi(self, resultwin):
        resultwin.setObjectName("resultwin")
        resultwin.resize(677, 457)
        font = QtGui.QFont()
        font.setPointSize(10)
        resultwin.setFont(font)
        self.centralwidget = QtWidgets.QWidget(resultwin)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(120, 110, 471, 161))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        resultwin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(resultwin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 677, 29))
        self.menubar.setObjectName("menubar")
        resultwin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(resultwin)
        self.statusbar.setObjectName("statusbar")
        resultwin.setStatusBar(self.statusbar)

        self.retranslateUi(resultwin)
        QtCore.QMetaObject.connectSlotsByName(resultwin)

    def retranslateUi(self, resultwin):
        _translate = QtCore.QCoreApplication.translate
        resultwin.setWindowTitle(_translate("resultwin", "Result"))
        self.label.setText(_translate("resultwin", "Имя:"))
        self.label_2.setText(_translate("resultwin", "Потрачено времени::"))
        self.label_3.setText(_translate("resultwin", "Количество правильных ответов:"))
        self.lineEdit.setText(str(self.name))
        self.lineEdit_2.setText(str(self.S3))
        self.lineEdit_3.setText(str(self.total))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    resultwin = QtWidgets.QMainWindow()
    ui = Ui_resultwin()
    ui.setupUi(resultwin)
    resultwin.show()
    sys.exit(app.exec_())
